name: smart_waste_management_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_local_notifications: ^9.1.4
  http: ^0.13.4
  geolocator: ^9.0.2
  firebase_core: ^2.10.0
  firebase_messaging: ^14.6.3
  provider: ^6.0.5
  fl_chart: ^0.40.0

flutter:
  uses-material-design: true
