name: smart_waste_management_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_local_notifications: ^17.2.1+1
  http: ^1.2.1
  geolocator: ^12.0.0
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  provider: ^6.0.5
  fl_chart: ^0.68.0
  sqflite: ^2.0.0+3
  path: ^1.8.1

flutter:
  assets:
    - assets/trash_icon.png

  uses-material-design: true
